In [44]:
from tensorflow.contrib import slim
from sklearn.metrics import precision_recall_fscore_support as score
import tensorflow as tf
import numpy as np

In [26]:
# logits = tf.Variable([[0.1, 0.5, 0.4],
#       [0.8, 0.1, 0.1],
#       [0.6, 0.3, 0.2]])
# labels = tf.Variable([[0, 1, 0],
#       [1, 0, 0],
#       [0, 0, 1]])
# labels=tf.argmax(labels, 0)
# predictions=tf.argmax(logits,0)

labels = tf.Variable([0, 1, 2, 0, 1, 2])
predictions = tf.Variable([0, 2, 1, 0, 0, 1])

In [27]:
acc, acc_op = tf.metrics.precision(labels,predictions)
sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
tf.local_variables_initializer().run()
print(sess.run([acc, acc_op]))
print(sess.run([acc]))
confusion = tf.confusion_matrix(labels=labels, predictions=predictions, num_classes=3)
print(sess.run(confusion))
# Output
#[0.0, 0.66666669]
#[0.66666669]

[0.0, 1.0]
[1.0]
[[2 0 0]
 [1 0 1]
 [0 2 0]]


In [48]:
labels = [0, 1, 2, 0, 1, 2]
predictions = [0, 2, 1, 0, 0, 1]

precision, recall, f1, _ = score(labels, predictions)
print('precision: {}'.format(precision))
print('precision: {}'.format(np.mean(precision)))
print('recall: {}'.format(recall))
print('precision: {}'.format(np.mean(recall)))
print('fscore: {}'.format(f1))

precision: [0.66666667 0.         0.        ]
precision: 0.222222222222
recall: [1. 0. 0.]
precision: 0.333333333333
fscore: [0.8 0.  0. ]


In [24]:
# Choose the metrics to compute:
names_to_values, names_to_updates = slim.metrics.aggregate_metric_map({
    "accuracy": tf.metrics.accuracy(labels, predictions),
    'precision': tf.metrics.precision(labels, predictions),
#     'Recall@1': tf.metrics.recall_at_k(labels, logits, 1)
})

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    tf.local_variables_initializer().run()
    sess.run(names_to_updates.values())
#     print(sess.run(names_to_values.values()))
    for metric_name, metric_value in names_to_values.iteritems():
        print(metric_name, sess.run(metric_value))


('precision', 1.0)
('accuracy', 0.33333334)


Tensor("confusion_matrix/SparseTensorDenseAdd:0", shape=(3, 3), dtype=int32)
